version = 0.1
[default.deploy.parameters]
stack_name = "eda-s3-eventbridge-stack"
resolve_s3 = true
s3_prefix = "eda-s3-eventbridge-stack"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
