AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  EdaS3Lambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: lambda-eda-s3-event
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      CodeUri: .
      MemorySize: 256
      Timeout: 30
      Policies:
        - AmazonS3ReadOnlyAccess
        - CloudWatchLogsFullAccess
        - AWSLambdaBasicExecutionRole
      Events:
        S3UploadTrigger:
          Type: EventBridgeRule
          Properties:
            Pattern:
              source:
                - aws.s3
              detail-type:
                - "Object Created"
              detail:
                bucket:
                  name:
                    - diners-poc
                object:
                  key:
                    - suffix: ".csv"